backend/src/main/java/com/minionz/backend/common/domain/Address.java
backend/src/main/java/com/minionz/backend/user/controller/UserController.java
backend/src/main/java/com/minionz/backend/user/controller/dto/UserJoinRequestDto.java
backend/src/main/java/com/minionz/backend/user/domain/UserRepository.java
backend/src/main/java/com/minionz/backend/user/service/UserService.java
backend/src/main/java/com/minionz/backend/visit/service/VisitService.java
backend/src/test/java/com/minionz/backend/user/controller/UserControllerTest.java
backend/src/test/java/com/minionz/backend/user/controller/UserRepositoryTest.java
backend/src/test/java/com/minionz/backend/user/service/UserServiceTest.java

[BE] 회원가입, 탈퇴 기능 수정

---

src/main/asciidoc/index.adoc
src/main/java/com/minionz/backend/shop/controller/ShopController.java
src/main/java/com/minionz/backend/shop/controller/dto/ShopListResponseDto.java
src/main/java/com/minionz/backend/shop/service/ShopService.java
src/test/java/com/minionz/backend/shop/controller/ShopControllerTest.java

[BE] 매장리스트 기능 추가

---

src/main/asciidoc/index.adoc
src/main/java/com/minionz/backend/shop/controller/ShopController.java
src/main/java/com/minionz/backend/shop/controller/dto/CommonShopResponseDto.java
src/main/java/com/minionz/backend/shop/service/ShopService.java
src/main/java/com/minionz/backend/user/controller/UserController.java
src/main/java/com/minionz/backend/user/service/UserService.java
src/test/java/com/minionz/backend/ApiDocument.java
src/test/java/com/minionz/backend/EnableMockMvc.java
src/test/java/com/minionz/backend/shop/controller/ShopControllerTest.java
src/test/java/com/minionz/backend/user/controller/UserControllerTest.java

[BE] 메인페이지, 검색 docs 작성 

---

src/main/asciidoc/index.adoc
src/main/java/com/minionz/backend/shop/controller/ShopController.java
src/main/java/com/minionz/backend/shop/controller/dto/ShopDetailResponseDto.java
src/main/java/com/minionz/backend/shop/controller/dto/ShopTableCountResponseDto.java
src/main/java/com/minionz/backend/shop/service/ShopService.java
src/test/java/com/minionz/backend/shop/controller/ShopControllerTest.java

[BE] 매장 상세보기(공통) docs

---

src/main/java/com/minionz/backend/shop/controller/ShopController.java
src/test/java/com/minionz/backend/shop/controller/ShopControllerTest.java

[BE] ShopController 수정 

---

src/main/java/com/minionz/backend/shop/controller/dto/CommonShopResponseDto.java
src/main/java/com/minionz/backend/shop/domain/Shop.java
src/main/java/com/minionz/backend/user/controller/UserController.java
src/main/java/com/minionz/backend/user/controller/dto/BookmarkRequestDto.java
src/main/java/com/minionz/backend/user/service/UserService.java
src/test/java/com/minionz/backend/shop/controller/ShopControllerTest.java
src/test/java/com/minionz/backend/user/controller/UserControllerTest.java
src/test/java/com/minionz/backend/user/service/UserServiceTest.java

[BE] 즐겨찾기 기능구현

---

src/main/java/com/minionz/backend/shop/controller/ShopController.java
src/main/java/com/minionz/backend/shop/service/ShopService.java
src/test/java/com/minionz/backend/shop/service/ShopServiceTest.java

[BE] Owner 매장 상세보기 기능 추가

---

src/main/java/com/minionz/backend/shop/controller/ShopController.java
src/main/java/com/minionz/backend/shop/controller/dto/CommonShopResponseDto.java
src/main/java/com/minionz/backend/shop/domain/Shop.java
src/main/java/com/minionz/backend/shop/domain/ShopRepository.java
src/main/java/com/minionz/backend/shop/service/ShopService.java
src/test/java/com/minionz/backend/shop/controller/ShopControllerTest.java
src/test/java/com/minionz/backend/shop/service/ShopServiceTest.java

[BE] 매장 검색 기능구현 

---

src/main/asciidoc/index.adoc
src/main/java/com/minionz/backend/shop/controller/ShopController.java
src/main/java/com/minionz/backend/shop/domain/ShopRepository.java
src/main/java/com/minionz/backend/shop/service/ShopService.java
src/test/java/com/minionz/backend/shop/controller/ShopControllerTest.java
src/test/java/com/minionz/backend/shop/service/ShopServiceTest.java

[BE] 메인페이지 내 주변 매장 기능구현

---

src/main/java/com/minionz/backend/shop/controller/ShopTableController.java
src/main/java/com/minionz/backend/shop/domain/ShopTable.java
src/main/java/com/minionz/backend/shop/service/ShopTableService.java
src/test/java/com/minionz/backend/shop/service/ShopTableServiceTest.java

[BE] 퇴장 기능 추가

---

src/main/java/com/minionz/backend/shop/controller/dto/ShopDetailResponseDto.java
src/main/java/com/minionz/backend/shop/controller/dto/ShopTableCountResponseDto.java
src/main/java/com/minionz/backend/shop/domain/Shop.java
src/main/java/com/minionz/backend/shop/service/ShopService.java
src/main/java/com/minionz/backend/user/domain/BookmarkRepository.java
src/main/java/com/minionz/backend/user/domain/User.java
src/test/java/com/minionz/backend/shop/controller/ShopControllerTest.java
src/test/java/com/minionz/backend/shop/service/ShopServiceTest.java

[BE] 매장 상세보기(공통) 기능구현

---

src/main/java/com/minionz/backend/user/service/UserService.java
src/main/java/com/minionz/backend/visit/domain/Visit.java
src/test/java/com/minionz/backend/user/service/UserServiceTest.java

[BE] 마이페이지 내 방문 매장리스트 추가

---

src/main/java/com/minionz/backend/shop/domain/Shop.java
src/test/java/com/minionz/backend/shop/controller/ShopTableControllerTest.java
src/test/java/com/minionz/backend/user/service/UserServiceTest.java

[BE] 테스트 코드 에러 수정

---

src/main/java/com/minionz/backend/shop/domain/ShopRepository.java
src/main/java/com/minionz/backend/shop/service/ShopService.java

[BE] 매장 검색 지역 필터 기능 수정

---

src/main/java/com/minionz/backend/user/domain/User.java
src/main/java/com/minionz/backend/user/service/UserService.java

[BE] 즐겨찾기 등록, 삭제 버그 수정 

---

.travis.yml
appspec.yml
appspect.yml
scripts/deploy.sh

[BE] 배포 자동화(CI/CD)

---

src/main/java/com/minionz/backend/shop/controller/ShopController.java
src/main/java/com/minionz/backend/shop/controller/dto/NearShopResponseDto.java
src/main/java/com/minionz/backend/shop/service/ShopService.java
src/test/java/com/minionz/backend/shop/controller/ShopControllerTest.java
src/test/java/com/minionz/backend/shop/service/ShopServiceTest.java

[BE] 메인페이지 상점 조회 response 좌표값 추가

---

appspec.yml
build.gradle
scripts/deploy.sh
scripts/health.sh
scripts/profile.sh
scripts/start.sh
scripts/stop.sh
scripts/switch.sh
src/main/java/com/minionz/backend/common/controller/ProfileController.java
src/main/resources/application-real1.properties
src/main/resources/application-real2.properties
src/test/java/com/minionz/backend/common/controller/ProfileControllerTest.java
src/test/java/com/minionz/backend/common/controller/ProfileControllerUnitTest.java

[BE] 무중단 배포

---

src/main/java/com/minionz/backend/shop/domain/Shop.java
src/main/java/com/minionz/backend/user/domain/UserBaseEntity.java
src/main/java/com/minionz/backend/user/domain/UserRepository.java
src/main/java/com/minionz/backend/user/service/UserService.java

[BE] Unique 값 에러 메세지 response 

---

src/main/java/com/minionz/backend/shop/domain/ShopRepository.java

[BE] 주변 매장 조회 수정
